### ISSUE TITLE
`ubuntu-latest` + `gcc` seems to be no longer working.

### ISSUE THREAD

**Issue by loiseaujc** [fortran-lang/setup-fortran#101]
Hej,

I've using this action for a few weeks now and it worked perfectly until earlier today. Whenver I want to test my code with `ubuntu-latest` and `gcc` (whether it is 12 or 13), I get the following error:

 ```
Run fortran-lang/setup-fortran@main
Run action_path=$(echo '//home/runner/work/_actions/fortran-lang/setup-fortran/main' | sed -e 's/\\/\//g' -e 's/://')
+ compiler=gcc
++ uname -s
++ tr '[:upper:]' '[:lower:]'
+ platform=linux
+ [[ Linux == \m\a\c\O\S ]]
+ case $compiler in
+ version=12
+ install_gcc linux
+ local platform=linux
+ case $platform in
+ install_gcc_apt
++ apt show gcc
++ grep Version
++ cut -d: -f3
++ cut -d- -f1
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
+ cur=11.2.0
++ echo 11.2.0
++ cut -d. -f1
+ maj=11
+ '[' 11 == 12 ']'
+ sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 364, in <module>
    sys.exit(0 if addaptrepo.main() else 1)
  File "/usr/bin/add-apt-repository", line 347, in main
    shortcut = handler(source, **shortcut_params)
  File "/usr/lib/python3/dist-packages/softwareproperties/shortcuts.py", line 40, in shortcut_handler
    return handler(shortcut, **kwargs)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 82, in __init__
    if self.lpppa.publish_debug_symbols:
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 120, in lpppa
    self._lpppa = self.lpteam.getPPAByName(name=self.ppaname)
  File "/usr/lib/python3/dist-packages/lazr/restfulclient/resource.py", line [5](https://github.com/nekStab/LightKrylov/actions/runs/9599688291/job/26475970836#step:3:6)92, in __call__
    response, content = self.root._browser._request(
  File "/usr/lib/python3/dist-packages/lazr/restfulclient/_browser.py", line 429, in _request
    raise error
lazr.restfulclient.errors.ServerError: HTTP Error [50](https://github.com/nekStab/LightKrylov/actions/runs/9599688291/job/26475970836#step:3:52)3: Service Unavailable
Response headers:
---
-content-encoding: gzip
connection: close
content-length: 2155
content-type: text/html
date: Thu, 20 Jun 2024 15:31:32 GMT
server: Apache/2.4.41 (Ubuntu)
status: 503
vary: Accept-Encoding
---
Response body:
---
b'<!DOCTYPE html>\n<html\n  xmlns="http://www.w3.org/1999/xhtml"\n  xml:lang="en"\n  lang="en"\n>\n<head>\n  <title>Launchpad is temporarily unavailable</title>\n  <link\n    type="text/css" rel="stylesheet" media="screen, print"\n    href="https://launchpad.net/+icing/basic-error.css" />\n</head>\n<body>\n  <div class="page-center-wrap">\n    <div class="page-center">\n      <div class="page-center-content">\n        <div id="header">\n          <div class="graphic">\n            :(\n          </div>\n          <div class="content">\n            <!-- Before editing, please see\n                https://bugs.launchpad.net/bugs/47[53](https://github.com/nekStab/LightKrylov/actions/runs/9599688291/job/26475970836#step:3:55)71, especially comment #2,\n                for details on this file. In particular, please maintain the\n                \\r\\n line endings, at least for the HTTP header lines. -->\n            <h1>Uh oh!</h1>\n            <h2>Something has gone wrong. We\'re sorry!</h2>\n            <p>\n              If we are in the middle of an update, Launchpad will be\n              back in a
---
Error: Process completed with exit code 1.
```

I suppose this is related to `ubuntu-toolchain-r/test` ppa being removed from Ubuntu images as discussed [here](https://github.com/actions/runner-images/issues/9679).

**Comment by wpbonelli** [comment]
we [add the ppa](https://github.com/fortran-lang/setup-fortran/blob/8821f57b53846d35d62632eb51c60ac6c4bff4ce/setup-fortran.sh#L54) pretty sure this is a Canonical outage
* https://status.canonical.com/#/incident/KNms6QK9ewuzz-7xUsPsNylV20jEt5kyKsd8A-3ptQG9fRkoWF_tPwQo3xO6l_CBViNLhdmwjQX92RChV_TTHQ==
* https://status.canonical.com/#/incident/KNms6QK9ewuzz-7xUsPsNylV20jEt5kyKsd8A-3ptQH8iV1Ce9i60VpTCDM_mnuTt9N_QOCgYCPUsWYXPtnGVA==

**Comment by loiseaujc** [comment]
Awesome (kind of) ! I did not think about checking canonical' status. I guess it'll eventually get back online. Closing the issue then.
